import './globals.css'
import { GeistSans } from 'geist/font/sans';

export const metadata = {
  title: 'EMC Yoga School',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" className={GeistSans.className}>
      <body>{children}</body>
    </html>
  )
}
